### ISSUE TITLE
Bug: the walk mode shows the wrong directories for extra and save

### ISSUE THREAD

**Issue by sean-kang** [zanllp/sd-webui-infinite-image-browsing#108]
By default, Extra and Save directories do not have subdirectory structure as txt2img and img2img directories do. When a directory does not have subdirectory such as "2023-05-08", this extension shows the subdirectories of other random irrelevant directories in the walk mode.

For example, it shows "2023-05-09" directory in the walk mode for save directory although the directory does not have it. If I click it, it will forward me to the subdirectory of img2img or txt2img.

I am running SD on Linux. If this problem does not happen in other OS, it might be a path handling issue.

**Comment by zanllp** [comment]
I will delete both of them.

**Comment by zanllp** [comment]
> Can be possible to add "other" folders for walk mode?

You can temporarily enable walk mode to browse through specific folders, as shown in the screenshot below. However, please note that walk mode is currently specialized for use in the sd-webui and only handles a two-level tree structure, rather than a true DFS. Therefore, I cannot guarantee that it will work as well in other folders or situations

<img width="362" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/1317865e-b98e-42ca-ab21-e9db11d75ac6">

**Comment by meegle84** [comment]
oh, thanks!
that is what I was looking for. In my case is to browse txt2img in walk mode, so it works perfectly with two-level also in this case
