### ISSUE TITLE
[Bug] LoRA text not indexed for image search

### ISSUE THREAD

**Issue by TheSeventhCode** [zanllp/sd-webui-infinite-image-browsing#114]
I have the following LoRA usage in some of my images: `<lora:AnyaTaylorJoy_v1.11.0:0.6>`. When I index my images (even when completely rebuilding it, by deleting the database), the LoRA isn't recognized and doesn't show up as a tag.
Something like `<lora:epiNoiseoffset_v2:0.3>` isn't indexed either.

Is it because of the weights or something?

**Comment by zanllp** [comment]
No, it's supports weights. The first issue with Lora seems to be because I overlooked the possibility of using the '.' symbol when writing the regexp. This will be fixed in the future.
The second issue doesn't seem like it should be happening. It's behaving normally on my end. Perhaps it's because the correct commas weren't used before and after Lora?
Can you show me the full prompt?

<img width="482" alt="image" src="https://user-images.githubusercontent.com/25872019/236910519-fad6e4cb-5d52-488b-a809-ba8939efeb62.png">

**Comment by TheSeventhCode** [comment]
```
a photo of a woman (wearing cowboy clothes) standing outside, blue jeans jacket,
grey-white overcast, grey background,
ultra realistic, highly detailed, very real <lora:ATJ_v1.1:1.2>
Negative prompt: trees, bush, blue sky, individual clouds
```

Something like this.
The `ATJ_v1` won't show up as a LoRA option.
But yeah, it could be because of the missing comma at the end. But I hope this can be included; otherwise it would be a bit annoying to always make sure, the exact syntax/comma placing is correct.

**Comment by zanllp** [comment]
It's not because of the missing colon at the end - I would have handled that situation. Before, I thought that your Lora used a different symbol as a separator, such as a period.

Now it appears that it's because Lora and 'very real' were mixed together, and this is the first time I've seen this usage.

**Comment by zanllp** [comment]
I have implemented this. You can delete the iib.db file under the extension's root directory and regenerate the index.

<img width="1061" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/c4c6bdee-1aa3-45ab-80ba-5133d2c257cd">

**Comment by TheSeventhCode** [comment]
Thanks very much, this fixed it.
Now everything shows up and the different LoRA's are all listed.

also awesome extension in general!
