### ISSUE TITLE
Need Help Getting out of Access Control Mode

### ISSUE THREAD

**Issue by Anon001846** [zanllp/sd-webui-infinite-image-browsing#284]
Hello I haven't updated SD in a while, I recently updated this extension and get this message. 
"To ensure data security, you are currently running in access control mode, which only allows access to authorized folders. You can adjust the access permissions settings (IIB_ACCESS_CONTROL) by editing the .env file in the root directory of this extension. If the .env file does not exist, you can copy the .env.example file and rename it to .env."

I am using Runpod a virtual GPU space.  

<img width="400" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/121414722/67233bb1-3634-47f6-a945-9dd878a7d17b">

1. When I download the .env.example inside of my Juypter Labs folder it doesn't let me add a (.) in front of the file name
2. I cannot get the iib.db in the main folder open - unless I'm supposed to access it in the scripts folder? Where do I go to fill in this section (IIB_SECRET_KEY=) in the .env ?
4. If this cannot be fixed how can I revert this extension back if I am running Auto1111 v.1.3.2

Thank you

**Comment by zanllp** [comment]
Hi there! Based on your issue, it seems that you are looking to set the IIB_SECRET_KEY environment variable, but you're not sure where to do it because you cannot find the .env file.

Just to clarify, you don't necessarily need to set the IIB_SECRET_KEY in the .env file. Instead, you can set the corresponding environment variable directly. 

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/1f00bcba-1df8-4ee9-8493-b6c897f388d0)

 or 

```bash
IIB_ACCESS_CONTROL=disable IIB_SECRET_KEY=123456 && ./webui.sh
```

For more information on how to set environment variables, you can refer to our previous discussion on GitHub: https://github.com/zanllp/sd-webui-infinite-image-browsing/discussions/236

Let me know if you have any further questions or concerns!

**Comment by zanllp** [comment]
You can refer to this file for the relevant environment variable documentation: https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/main/.env.example

**Comment by Anon001846** [comment]
Thank you so much for your prompt response! After some tinkering around I got it to work! Much better UI than the original Image Gallery Viewer. Thank you for referencing the other thread. 🙏 Have an Awesome day! 😃

**Comment by Kornifikator** [comment]
I love when people say "thanks, I got it to run somehow. Have a great day" and then they don't describe the solution🤦‍♂️...Have you ever thought that the solution to your problem could be of interest to others too?!

So, how did you tinker around to get it to work? What did you do?
 

> Thank you so much for your prompt response! After some tinkering around I got it to work! Much better UI than the original Image Gallery Viewer. Thank you for referencing the other thread. 🙏 Have an Awesome day! 😃

**Comment by Kornifikator** [comment]
I love when people say "thanks, I got it to run somehow. Have a great day" and then they don't describe the solution🤦‍♂️...Have you ever thought that the solution to your problem could be of interest to others too?!

So, how did you tinker around to get it to work? What did you do?



> Thank you so much for your prompt response! After some tinkering around I got it to work! Much better UI than the original Image Gallery Viewer. Thank you for referencing the other thread. 🙏 Have an Awesome day! 😃
