### ISSUE TITLE
Clarification on "Quick Move"

### ISSUE THREAD

**Issue by james81553** [zanllp/sd-webui-infinite-image-browsing#285]
Hi,

I just wanted to clarify that "Quick Move" means that I quickly move to that folder for browsing, and it's not about moving files or images to another folder?

If's its about quick browsing of another folder, than I'd love to see the feature added so files can moved (or copied) to another folder other than just 'saves'.

Thanks.

![QuickMove](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/138188601/22b41a44-e605-49d0-a2d7-fe262df6abb3)

**Comment by zanllp** [comment]
"Quick Move" refers to quickly navigating to another folder  , rather than moving files to a different folder. If you want to move files to a specific folder, you can open a new tab and use drag and drop to move the files between different folders.

You can refer to the video in the readme for instructions on how to operate.
<img width="674" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/7cff59be-3513-45ad-8451-e5956c96a655">

**Comment by zanllp** [comment]
"Quick Move" seems to have some ambiguity as the name of this feature, I will change it in a moment.

**Comment by james81553** [comment]
Thanks for clarifying all that.
