### ISSUE TITLE
Errors during folder browsing

### ISSUE THREAD

**Issue by ostap667inbox** [zanllp/sd-webui-infinite-image-browsing#35]
This is what is displayed in the console while navigating through folders and viewing pictures.
I see a strange presence of baidu_netdisk in the error:
````API error: GET: http://127.0.0.1:7860/baidu_netdisk/file?filename=C%3A%5CSD_MY%5C21 {'error': 'RuntimeError', 'detail': '', 'body': '', 'errors': 'File at path C:\\SD_MY\\21 is not a file.'}````

Or reports an error that the folder is not a file :)
````RuntimeError: File at path C:\SD_MY\34_Elldreths Retro Mix is not a file.````
_(34_Elldreths Retro Mix - is folder name)_

![error](https://user-images.githubusercontent.com/123593542/233780194-dcea99ba-5d78-4ab7-942e-a4da7ee92baf.png)

**Comment by zanllp** [comment]
"baidu_netdisk" is the prefix for API requests in this project, which was the earliest feature of this project. It has now become an optional feature, but the API request prefix has been retained. I will replace it with "infinite-image-browsing" in the near future.

I have also encountered this error a few times, but it does not affect the functionality, and I have been focusing all my energy on developing image search recently, so I haven't had the extra time to fix it yet now.

**Comment by ostap667inbox** [comment]
> I have also encountered this error a few times, but it does not affect the functionality, and I have been focusing all my energy on developing image search recently, so I haven't had the extra time to fix it yet now.

Yes, it does not affect the functionality

**Comment by zanllp** [comment]
Due to concerns that "baidu_netdisk" might cause unnecessary misunderstandings, I temporarily merged #31. You can also try to upgrade, although it doesn't fix any bugs, it removes a lot of unnecessary "baidu_netdisk" and brings a very fast image search function.
Here is the new URL for calling stable-diffusion-webui.

<img width="743" alt="image" src="https://user-images.githubusercontent.com/25872019/233784119-2e059780-2915-4a80-8d44-d497f1d70e02.png">
