### ISSUE TITLE
Feature request: Add favorite system to save images

### ISSUE THREAD

**Issue by dexyel** [zanllp/sd-webui-infinite-image-browsing#40]
Hey ! I noticed you have a folder under /log to save images. Could you add a "Add to favorites" button, either in the the contextual menu you get on an image or perhaps a button overlay when you hover over an image, that'll add any selected images to that folder or maybe a custom one ? This would be a great function.

Also and unrelated, could you increase the opacity of the dark background that appears on viewer mode? Right now it's a bit hard to see it's a new window on top of the UI.

Thanks :)

**Comment by zanllp** [comment]
I will implement a favorite function, but instead of moving/copying the image to the specified folder.
Instead you can add tags to the images via the right-click menu such as 'fav', 'like' etc. (you can customize this tag).
Then you can select these tags on the image search page and it will show you which images you want.
How do you feel about this? This is done to make it easier to search for images using multiple tags at the same time.
For example, you can use 'like', 'sky', 'Counterfeit-V2.5' at the same time to quickly find the image you need.

**Comment by zanllp** [comment]
I will implement a favorite function, but instead of moving/copying the image to the specified folder.
Instead you can add tags to the images via the right-click menu such as 'fav', 'like' etc. (you can customize this tag).
Then you can select these tags on the image search page and it will show you which images you want.
How do you feel about this? This is done to make it easier to search for images using multiple tags at the same time.
For example, you can use 'like', 'sky', 'Counterfeit-V2.5' at the same time to quickly find the image you need.

**Comment by zanllp** [comment]
If you really need to move the selected files to a specific folder, you can do it like this.


https://user-images.githubusercontent.com/25872019/234009947-7d9d5ffc-1f13-4edc-9299-74e1d0b8b60c.mp4

**Comment by zanllp** [comment]
More than one person requested this feature, so I added it.
<img width="326" alt="image" src="https://user-images.githubusercontent.com/25872019/234358179-ecea549d-8146-4459-942f-cbf9bf2008e0.png">
