### ISSUE TITLE
Not comfortable with upload functionality

### ISSUE THREAD

**Issue by nonnull-ca** [zanllp/sd-webui-infinite-image-browsing#41]
At a first glance, this looks great. But it - assuming I have correctly read the code (I haven't run it because of the below:)

1. [Autodownloads](https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/main/scripts/bin.py#L34) "BaiduPCS-Go", which is a library (?) I can find little-to-no English-language references to, from either github (sure) or a random HTTP .cn domain, with no signing (!!). An adversary could easily fail the github download and then respond with whatever they wished for the second download.
2. Ditto, I have little-to-no method of verifying that BaiduPCS-Go, even when properly installed, isn't doing anything nefarious. It is a large library in a language I don't speak, that intrinsically has network functionality, from - assuming "Baidu" is in fact the same company - a company that [has been caught doing nefarious things](https://citizenlab.ca/2016/02/privacy-security-issues-baidu-browser/) in the past.
3. Has a bunch of functionality around [uploading](https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/main/scripts/baiduyun_task.py#L107) files, including references to [autouploading](https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/main/scripts/api.py#L472).
4. Has classic parent-directory-traversal vulnerabilities in e.g. [file deletion](https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/c08b5dc9f68c5c901d845ecece8682ac0de3c261/scripts/api.py#L269). Admittedly, said API is not safe in general, but still worth noting.

Could non-local functionality please be broken out into a separate extension?

**Comment by zanllp** [comment]
the current data transfer function does bring unnecessary burden to users of this plugin （The number of stars in this repository has been growing slowly, and it is unclear whether this is related to it or not ， 😄.）

 Therefore, I will fork this repository and maintain the data transfer function separately. This project will only keep a link to the new repo.



1. "BaiduPCS-Go" is indeed used as a library, similar to "git" or "ffmpeg". It is normal that this repository does not have English documentation because it is mostly popular in China.
2. Dependencies will not be automatically downloaded and need to be manually installed by users. 
https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/c08b5dc9f68c5c901d845ecece8682ac0de3c261/vue/src/page/fileTransfer/stackView.vue#L65   

https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/c08b5dc9f68c5c901d845ecece8682ac0de3c261/scripts/api.py#L506-L511

4. "static.zanlp.cn" is not a random domain, it is my own domain, as you can see from my GitHub username. I did this because there are some regions in China where the connection to GitHub is not very stable.

**Comment by zanllp** [comment]
The data-transfer part has been separated out, and I have added hash verification to the files I downloaded.
 Thank you for your suggestion, I didn't think of this before.

https://github.com/zanllp/sd-webui-baidu-netdisk/blob/96a4e99d8cd8b470397a7b8ca26eff131d0d8d48/scripts/baidu_netdisk/bin.py#L11-L70

**Comment by PaperOrb** [comment]
@nonnull-ca sorry, I'm having a hard time following since I'm not an experienced coder. Regarding your points, I have some questions:
1. I assume point one wasn't addressed since it still uses BaiduPCS-Go? Did you skip this project due to that? I have my own security concerns.
2. He said he added hash verification on the downloaded files,, but I'm assuming you also wanted him to use HTTPS to transfer the files when you mentioned it being an "insecure method?"
3. Are you referring to the fact that the extension has access to the root folder? I was pretty taken aback when I saw my root folder pop up in the webui.
