### ISSUE TITLE
[Feature Request] Add Support for WebUI's --subpath Option

### ISSUE THREAD

**Issue by voronin-ilya** [zanllp/sd-webui-infinite-image-browsing#523]
### Context and Observed Behavior:

We are operating Stable Diffusion WebUI in a complex multi-user environment, which necessitates the use of URL prefixes for each user session. WebUI accommodates this scenario with the `--subpath` [option](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/cf2772fab0af5573da775e7437e6acdca424f26e/webui.py#L44), enabling it to properly manage requests directed to a non-root URL. Unfortunately, the Infinite Image Browsing extension does not support such scenarios due to hardcoded URL paths:

https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/0d09f47c95b1f43db30e19bd3c20b33b3e4fb363/javascript/index.js#L15
https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/0d09f47c95b1f43db30e19bd3c20b33b3e4fb363/vue/src/api/index.ts#L16
https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/0d09f47c95b1f43db30e19bd3c20b33b3e4fb363/vue/src/page/SplitViewTab/emptyStartup.vue#L89

etc.

### Desired Behavior:

Enable Infinite Image Browsing to correctly handle the `--subpath` option passed to the Web UI, or alternatively, use relative URLs.

**Comment by zanllp** [comment]
I will try to implement this feature.

**Comment by zanllp** [comment]
Already supported

<img width="841" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/544ec4ea-4a95-4f9a-93a9-300ef98d9644">

**Comment by voronin-ilya** [comment]
It works because, in your case, the browser can still access the Web UI by using non-prefixed URLs like '/infinite_image_browsing'. In our environment, only traffic to '/cxx/*' can actually reach the Web UI, due to reverse proxying with rules like this:
```
location = /cxx {
    proxy_pass http://webui-host:88/cxx/
}
```

**Comment by zanllp** [comment]
Here is our configuration file for Nginx. I followed this page as a reference: https://www.gradio.app/guides/running-gradio-on-your-web-server-with-nginx. I used port 88 because I was developing on WSL and couldn't directly use port 80.

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/271b6a4e-4527-4f4a-8e9a-b9bf9f4e7751)

Without the prefix, accessing IIB directly on my end results in a 404 error.

<img width="763" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/ab637ccd-d411-4866-a3d4-76dd645f2c12">

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/96067e9c-c4bf-4ab7-9f3d-ef8bd51b0392)

**Comment by zanllp** [comment]
Weirdly, I restarted the machine and it works perfectly now. It hadn't worked the past couple of times I started a new machine, but whatever was happening was fixed.

**Comment by zanllp** [comment]
If you have any more questions, please reopen this issue
