### ISSUE TITLE
API Error on SD Next

### ISSUE THREAD

**Issue by MysticDaedra** [zanllp/sd-webui-infinite-image-browsing#570]
I keep getting errors in console related to IIB. SD.next also crashed my PC a bit ago, possibly also related to IIB, not sure. Anyways, here's the log file.
[sdnext.log](https://github.com/zanllp/sd-webui-infinite-image-browsing/files/14809741/sdnext.log)

**Comment by zanllp** [comment]
These warnings and errors are from another image browser, right? I didn't see any information related to IIB.

**Comment by zanllp** [comment]
I added a handling for the error based on the information below, but there is not enough provided information for me to be certain if it can solve the problem. It would be helpful if I could see the corresponding call stack. I have not encountered this issue before, so it's possible that it's due to encountering an unexpected format during parsing.
<img width="1537" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/eabc8394-a4de-44c4-9662-57965e7b9778">

**Comment by zanllp** [comment]
Update to the latest version.
