### ISSUE TITLE
Feature request: Add password protection to the url

### ISSUE THREAD

**Issue by YamiZee** [zanllp/sd-webui-infinite-image-browsing#67]
With the automatic1111 web ui you have the option to use these parameters: 
--listen --gradio-auth someUsername:somePassword
This broadcasts web ui in the lan and allows other computers to connect with it, but once they do, they have to input the correct username and password. However this extension broadcasts a url like: http://192.168.0.12:7860/infinite_image_browsing which does not use the gradio auth username and password. This is a security issue, as simply having the correct url means anyone can view (and delete) any and every file on your device. If someone knows you use stable diffusion, it's not a difficult thing to guess.

Please add an option to either:
1. Disable the ability to access this extension directly through a url
2. Add password protection to the url

Note this should also apply to every other api access as well, such as:
http://192.168.0.12:7860/infinite_image_browsing/file?filename=C%3A%5Csd-outputs%5Cimage.png

**Comment by zanllp** [comment]
It seems to be an issue. I will try to add it later when I have time. If more people need it, I can implement it earlier.

**Comment by thesomeotherguy** [comment]
> Thank you for your feedback. I will try to add this feature at some point in the future. As the current usage is low and I haven't used the feature myself, the priority is not very high. If more users need this feature, I will implement it as soon as possible.

hello, first of all thank you for your hard work.. this extension really does awesome thing, because it helps browsing images so fast and stable.

but I agree with @YamiZee, sadly it is really security risk using this extension, in my opinion, it's not about high-low usage of this scenario. 

It can become a huge problem, not only on internal LAN, but also when we open our webui to the big bad internet like cloudflare tunnel or gradio app, everyone can access all of our files in all drives, and possibly can delete it.

I just realize this, that everyone can access my files when adding :7860/infinite_image_browsing on my IP or website/tunnel, without any login prompt at all.

take your time, but I do hope it will be addressed sometime later. many thanks.

**Comment by zanllp** [comment]
> > Thank you for your feedback. I will try to add this feature at some point in the future. As the current usage is low and I haven't used the feature myself, the priority is not very high. If more users need this feature, I will implement it as soon as possible.
> 
> hello, first of all thank you for your hard work.. this extension really does awesome thing, because it helps browsing images so fast and stable.
> 
> but I agree with @YamiZee, sadly it is really security risk using this extension, in my opinion, it's not about high-low usage of this scenario.
> 
> It can become a huge problem, not only on internal LAN, but also when we open our webui to the big bad internet like cloudflare tunnel or gradio app, everyone can access all of our files in all drives, and possibly can delete it.
> 
> I just realize this, that everyone can access my files when adding :7860/infinite_image_browsing on my IP or website/tunnel, without any login prompt at all.
> 
> take your time, but I do hope it will be addressed sometime later. many thanks.

I am aware that this feature is important. However, there are several major issues with the current extension, so I have not released an official version yet. This feature will be implemented at the same time as #116, which is also aimed at enhancing security. I will release an official version after completing these two features.

This extension is also quite strange to me. I don't know why there are so many feature requests, several of them are submitted on GitHub every day, it feels like there are more requests than most projects with around 1000 stars. Moreover, all the requests from users are useful, so I try to implement them all. Since this feature is more complex to implement than others and can be partially avoided, I will not be able to complete it quickly.

Currently, my priorities are:
1. A new caching mechanism that is more secure and does not require special settings
2. Adding support for custom folders in "quick move" and image search

If you are using a public network, I recommend not leaking your URL.

**Comment by zanllp** [comment]
@YamiZee @thesomeotherguy 

This feature has already been implemented.

see https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/131
